name: CI

on: [push, workflow_dispatch]

jobs:
  bootstrap-on-ubuntu:
    name: Ubuntu
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the code
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.3

    - name: Install dotfiles
      run: ./bootstrap.sh

  bootstrap-on-macos:
    name: macOS
    runs-on: macos-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Install dotfiles
        run: ./bootstrap.sh
